### ISSUE TITLE
reactide is not setting up in windows 10

### ISSUE THREAD

**Issue by sanjeev2552** [reactide/reactide#184]
I have recently cloned Reactide but after executing following commads
<pre>
git checkout 3.0-release
yarn install
yarn run build
</pre>
I got following error:
<pre>
    $ yarn run build
    yarn run v1.21.1
    $ electron-builder
      • electron-builder version=20.44.4
      • loaded configuration file=package.json ("build" field)
      • writing effective config file=release-builds\builder-effective-config.yaml
      • no native production dependencies
      • packaging       platform=win32 arch=x64 electron=3.1.13 appOutDir=release-bu
    ilds\win-unpacked
    panic: runtime error: index out of range

    goroutine 1 [running]:
    github.com/develar/app-builder/pkg/icons.doConvertIcon(0xc000061440, 0x4, 0x4, 0
    xc000130bc0, 0x2, 0x2, 0xc0000640a0, 0x3, 0xc00006a050, 0x45, ...)
            /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:223 +0xf
    20
    github.com/develar/app-builder/pkg/icons.ConvertIcon(0xc000061340, 0x0, 0x0, 0x0
    )
            /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56 +0xdd
    github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1(0xc00019fb90, 0x
    409e4a, 0xb440c0)
            /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33 +0x75
    github.com/alecthomas/kingpin.(*actionMixin).applyActions(0xc0000c8c18, 0xc00019
    fb90, 0x0, 0x0)
            /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
    le/actions.go:28 +0x74
    github.com/alecthomas/kingpin.(*Application).applyActions(0xc0000ca690, 0xc00019
    fb90, 0x0, 0x0)
            /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
    le/app.go:557 +0xe3
    github.com/alecthomas/kingpin.(*Application).execute(0xc0000ca690, 0xc00019fb90,
     0xc0001b4b30, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1)
            /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
    le/app.go:390 +0x96
    github.com/alecthomas/kingpin.(*Application).Parse(0xc0000ca690, 0xc0000a0010, 0
    x9, 0xf, 0xc0000ca690, 0xc0001dbf88, 0x405846, 0xc000056058)
            /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatib
    le/app.go:222 +0x20a
    main.main()
            /Volumes/data/Documents/app-builder/main.go:78 +0x34a
    Error: C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-bin
    \win\x64\app-builder.exe exited with code 2
        at ChildProcess. (C:\Users\Admin\Desktop\React Course\reactide\no
    de_modules\builder-util\src\util.ts:244:14)
        at Object.onceWrapper (events.js:300:26)
        at ChildProcess.emit (events.js:210:5)
        at maybeClose (internal/child_process.js:1021:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
    From previous event:
        at WinPackager.resolveIcon (C:\Users\Admin\Desktop\React Course\reactide\nod
    e_modules\app-builder-lib\src\platformPackager.ts:594:101)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\platformPackager.ts:573:31
        at Generator.next ()
    From previous event:
        at WinPackager.getOrConvertIcon (C:\Users\Admin\Desktop\React Course\reactid
    e\node_modules\app-builder-lib\src\platformPackager.ts:572:54)
        at Lazy. (C:\Users\Admin\Desktop\React Course\reactide\node_modul
    es\app-builder-lib\src\winPackager.ts:79:43)
        at Lazy.get value [as value] (C:\Users\Admin\Desktop\React Course\reactide\n
    ode_modules\lazy-val\src\main.ts:18:25)
        at WinPackager.getIconPath (C:\Users\Admin\Desktop\React Course\reactide\nod
    e_modules\app-builder-lib\src\winPackager.ts:190:27)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\winPackager.ts:287:33
        at Generator.next ()
    From previous event:
        at WinPackager.signAndEditResources (C:\Users\Admin\Desktop\React Course\rea
    ctide\node_modules\app-builder-lib\src\winPackager.ts:260:158)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\winPackager.ts:362:21
        at go$readdir$cb (C:\Users\Admin\Desktop\React Course\reactide\node_modules\
    graceful-fs\graceful-fs.js:187:14)
        at FSReqCallback.oncomplete (fs.js:146:23)
    From previous event:
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\winPackager.ts:360:27
        at Generator.next ()
    From previous event:
        at WinPackager.signApp (C:\Users\Admin\Desktop\React Course\reactide\node_mo
    dules\app-builder-lib\src\winPackager.ts:354:73)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\platformPackager.ts:250:16
        at Generator.next ()
        at processImmediate (internal/timers.js:439:21)
    From previous event:
        at WinPackager.doPack (C:\Users\Admin\Desktop\React Course\reactide\node_mod
    ules\app-builder-lib\src\platformPackager.ts:167:165)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\platformPackager.ts:113:16
        at Generator.next ()
    From previous event:
        at WinPackager.pack (C:\Users\Admin\Desktop\React Course\reactide\node_modul
    es\app-builder-lib\src\platformPackager.ts:111:95)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\packager.ts:430:24
        at Generator.next ()
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\fs-extra-p\node
    _modules\fs-extra\lib\mkdirs\mkdirs.js:56:16
        at callback (C:\Users\Admin\Desktop\React Course\reactide\node_modules\grace
    ful-fs\polyfills.js:295:20)
        at FSReqCallback.oncomplete (fs.js:159:5)
    From previous event:
        at Packager.doBuild (C:\Users\Admin\Desktop\React Course\reactide\node_modul
    es\app-builder-lib\src\packager.ts:396:24)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\packager.ts:366:57
        at Generator.next ()
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\graceful-fs\gra
    ceful-fs.js:136:16
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\graceful-fs\gra
    ceful-fs.js:57:14
        at FSReqCallback.oncomplete (fs.js:146:23)
    From previous event:
        at Packager._build (C:\Users\Admin\Desktop\React Course\reactide\node_module
    s\app-builder-lib\src\packager.ts:335:133)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-builder-lib
    \src\packager.ts:331:23
        at Generator.next ()
        at processImmediate (internal/timers.js:439:21)
    From previous event:
        at Packager.build (C:\Users\Admin\Desktop\React Course\reactide\node_modules
    \app-builder-lib\src\packager.ts:288:14)
        at build (C:\Users\Admin\Desktop\React Course\reactide\node_modules\app-buil
    der-lib\src\index.ts:59:28)
        at build (C:\Users\Admin\Desktop\React Course\reactide\node_modules\electron
    -builder\src\builder.ts:228:10)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\electron-builde
    r\src\cli\cli.ts:49:19
    error Command failed with exit code 1.
</pre>
I have also tried following command:
<pre>
git checkout 3.0-release
yarn install
yarn run webpack-production
</pre>
But got following error:
<pre>
    $ yarn run webpack-production
    yarn run v1.21.1
    $ webpack --mode production
    C:\Users\Admin\Desktop\React Course\reactide\node_modules\webpack-cli\bin\cli.js
    :281
                                    throw err;
                                    ^

    Error: Cannot find module 'monaco-editor\esm\vs\editor\contrib\gotoSymbol\goToCo
    mmands'
    Require stack:
    - C:\Users\Admin\Desktop\React Course\reactide\node_modules\monaco-editor-webpac
    k-plugin\out\index.js
    - C:\Users\Admin\Desktop\React Course\reactide\webpack.config.js
    - C:\Users\Admin\Desktop\React Course\reactide\node_modules\webpack-cli\bin\util
    s\convert-argv.js
    - C:\Users\Admin\Desktop\React Course\reactide\node_modules\webpack-cli\bin\cli.
    js
    - C:\Users\Admin\Desktop\React Course\reactide\node_modules\webpack\bin\webpack.
    js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
        at Function.resolve (C:\Users\Admin\Desktop\React Course\reactide\node_modul
    es\v8-compile-cache\v8-compile-cache.js:166:23)
        at resolveMonacoPath (C:\Users\Admin\Desktop\React Course\reactide\node_modu
    les\monaco-editor-webpack-plugin\out\index.js:26:20)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\monaco-editor-w
    ebpack-plugin\out\index.js:161:63
        at Array.map ()
        at createLoaderRules (C:\Users\Admin\Desktop\React Course\reactide\node_modu
    les\monaco-editor-webpack-plugin\out\index.js:161:43)
        at MonacoEditorWebpackPlugin.apply (C:\Users\Admin\Desktop\React Course\reac
    tide\node_modules\monaco-editor-webpack-plugin\out\index.js:80:23)
        at webpack (C:\Users\Admin\Desktop\React Course\reactide\node_modules\webpac
    k\lib\webpack.js:51:13)
        at processOptions (C:\Users\Admin\Desktop\React Course\reactide\node_modules
    \webpack-cli\bin\cli.js:272:16)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\webpack-cli\bin
    \cli.js:364:3
        at Object.parse (C:\Users\Admin\Desktop\React Course\reactide\node_modules\w
    ebpack-cli\node_modules\yargs\yargs.js:567:18)
        at C:\Users\Admin\Desktop\React Course\reactide\node_modules\webpack-cli\bin
    \cli.js:49:8
        at Object. (C:\Users\Admin\Desktop\React Course\reactide\node_mod
    ules\webpack-cli\bin\cli.js:366:3)
        at Module._compile (internal/modules/cjs/loader.js:959:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Function.Module._load (internal/modules/cjs/loader.js:727:14)
        at Module.require (internal/modules/cjs/loader.js:852:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object. (C:\Users\Admin\Desktop\React Course\reactide\node_mod
    ules\webpack\bin\webpack.js:156:2)
        at Module._compile (internal/modules/cjs/loader.js:959:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Function.Module._load (internal/modules/cjs/loader.js:727:14)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
        at internal/main/run_main_module.js:17:11 {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        'C:\\Users\\Admin\\Desktop\\React Course\\reactide\\node_modules\\monaco-edi
    tor-webpack-plugin\\out\\index.js',
        'C:\\Users\\Admin\\Desktop\\React Course\\reactide\\webpack.config.js',
        'C:\\Users\\Admin\\Desktop\\React Course\\reactide\\node_modules\\webpack-cl
    i\\bin\\utils\\convert-argv.js',
        'C:\\Users\\Admin\\Desktop\\React Course\\reactide\\node_modules\\webpack-cl
    i\\bin\\cli.js',
        'C:\\Users\\Admin\\Desktop\\React Course\\reactide\\node_modules\\webpack\\b
    in\\webpack.js'
      ]
    }
    error Command failed with exit code 1.
</pre>

**Comment by Ke100n4ik** [comment]
+1

**Comment by patel-dilip** [comment]
Stuck with the same issue.
Any ideas or clarifications?

**Comment by patel-dilip** [comment]
Hi, got some idea for fixing this issue. 

An explanation is given here :
https://github.com/microsoft/monaco-editor-webpack-plugin/issues/92#issuecomment-571148323

**Comment by patel-dilip** [comment]
I changed the package.json file at line 50 & 51 :
    "monaco-editor": "^0.14.3",
    "monaco-editor-webpack-plugin": "^1.5.4",
with :
    "monaco-editor": "~0.14.3",
    "monaco-editor-webpack-plugin": "~1.5.4",

This change restricts the use of latest monaco-editor and its webpack-plugin.
Then run the command:
       yarn install
Then finally run your command:
       yarn run webpack-production

Hope this resolves your problem. It worked for me!
Thanks.

**Comment by sanjeev2552** [comment]
> I changed the package.json file at line 50 & 51 :
> "monaco-editor": "^0.14.3",
> "monaco-editor-webpack-plugin": "^1.5.4",
> with :
> "monaco-editor": "~0.14.3",
> "monaco-editor-webpack-plugin": "~1.5.4",
> 
> This change restricts the use of latest monaco-editor and its webpack-plugin.
> Then run the command:
> yarn install
> Then finally run your command:
> yarn run webpack-production
> 
> Hope this resolves your problem. It worked for me!
> Thanks.

Thanks a lot, it did worked for me as well.

**Comment by sanjeev2552** [comment]
My probelm is solve that's why I'm closing this issue.

**Comment by Bennyyoung** [comment]
> I changed the package.json file at line 50 & 51 : "monaco-editor": "^0.14.3", "monaco-editor-webpack-plugin": "^1.5.4", with : "monaco-editor": "~0.14.3", "monaco-editor-webpack-plugin": "~1.5.4",
> 
> This change restricts the use of latest monaco-editor and its webpack-plugin. Then run the command: yarn install Then finally run your command: yarn run webpack-production
> 
> Hope this resolves your problem. It worked for me! Thanks.

Thanks me too
