### ISSUE TITLE
Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'

### ISSUE THREAD

**Issue by gosiapolitowska** [reactide/reactide#187]
I was following instructions from readme but `npm run webpack-production` fails with following error:

```
$ npm run webpack-production

> reactide@3.0.0 webpack-production /home/marhewa/apps/reactide
> webpack --mode production

/home/marhewa/apps/reactide/node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (/home/marhewa/apps/reactide/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at resolveMonacoPath (/home/marhewa/apps/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:26:20)
    at use.options.pre.featurePaths.map (/home/marhewa/apps/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:161:63)
    at Array.map (<anonymous>)
    at createLoaderRules (/home/marhewa/apps/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:161:43)
    at MonacoEditorWebpackPlugin.apply (/home/marhewa/apps/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:80:23)
    at webpack (/home/marhewa/apps/reactide/node_modules/webpack/lib/webpack.js:51:13)
    at processOptions (/home/marhewa/apps/reactide/node_modules/webpack-cli/bin/cli.js:272:16)
    at yargs.parse (/home/marhewa/apps/reactide/node_modules/webpack-cli/bin/cli.js:364:3)
    at Object.parse (/home/marhewa/apps/reactide/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/marhewa/apps/reactide/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/marhewa/apps/reactide/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/marhewa/apps/reactide/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactide@3.0.0 webpack-production: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactide@3.0.0 webpack-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

OS: Linux Mint
npm version: 6.13.7

**Comment by andresmarin** [comment]
Same issue on Redhat

**Comment by andresmarin** [comment]
The solution is on #184

**Comment by shawnpringle** [comment]
Same issue on Windows 10

**Comment by vipul2008** [comment]
I was also facing same issue in Win10, and #184 solved the issue. Thanks @andresmarin
