### ISSUE TITLE
npm run webpack-production throws an exception

### ISSUE THREAD

**Issue by ketankshukla** [reactide/reactide#196]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack-production'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.5.0
4 verbose run-script [
4 verbose run-script   'prewebpack-production',
4 verbose run-script   'webpack-production',
4 verbose run-script   'postwebpack-production'
4 verbose run-script ]
5 info lifecycle reactide@3.0.0~prewebpack-production: reactide@3.0.0
6 info lifecycle reactide@3.0.0~webpack-production: reactide@3.0.0
7 verbose lifecycle reactide@3.0.0~webpack-production: unsafe-perm in lifecycle true
8 verbose lifecycle reactide@3.0.0~webpack-production: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ketans/projects/reactide/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc:/mnt/c/Python38/Scripts/:/mnt/c/Python38/:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Calibre2/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/windo/AppData/Local/Programs/Python/Python38-32/Scripts/:/mnt/c/Users/windo/AppData/Local/Programs/Python/Python38-32/:/mnt/c/Users/windo/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/JetBrains/PyCharm 2019.3.3/bin:/mnt/c/Users/windo/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/windo/AppData/Local/JetBrains/jdk8/jre/bin:/mnt/c/tools/dart-sdk/bin:/mnt/c/tools/flutter/bin:/mnt/c/Users/windo/AppData/Roaming/Pub/Cache/bin:/mnt/c/tools/flutter/:/mnt/c/Users/windo/AppData/Roaming/npm:/mnt/c/Users/windo/AppData/Local/GitHubDesktop/bin:/mnt/c/Python27/:/mnt/c/Python27/Scripts/
9 verbose lifecycle reactide@3.0.0~webpack-production: CWD: /home/ketans/projects/reactide
10 silly lifecycle reactide@3.0.0~webpack-production: Args: [ '-c', 'webpack --mode production' ]
11 silly lifecycle reactide@3.0.0~webpack-production: Returned: code: 1  signal: null
12 info lifecycle reactide@3.0.0~webpack-production: Failed to exec webpack-production script
13 verbose stack Error: reactide@3.0.0 webpack-production: `webpack --mode production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid reactide@3.0.0
15 verbose cwd /home/ketans/projects/reactide
16 verbose Linux 4.4.0-19041-Microsoft
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack-production"
18 verbose node v14.5.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error reactide@3.0.0 webpack-production: `webpack --mode production`
22 error Exit status 1
23 error Failed at the reactide@3.0.0 webpack-production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jerome-diver** [comment]
i see also all the bug deprectated list and i'm thinking this project is no more maintain and is now dead.

**Comment by ketankshukla** [comment]
What a shame. This could have been something.

**Comment by unajscom** [comment]
Got the same error

`reactide git:(3.0-release) npm run webpack-production

> reactide@3.0.0 webpack-production /Users/mmt8048/Desktop/dev/react-ide/reactide
> webpack --mode production

/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at resolveMonacoPath (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:26:20)
    at use.options.pre.featurePaths.map (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:161:63)
    at Array.map (<anonymous>)
    at createLoaderRules (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:161:43)
    at MonacoEditorWebpackPlugin.apply (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/monaco-editor-webpack-plugin/out/index.js:80:23)
    at webpack (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/webpack/lib/webpack.js:51:13)
    at processOptions (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/webpack-cli/bin/cli.js:272:16)
    at yargs.parse (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/webpack-cli/bin/cli.js:364:3)
    at Object.parse (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/yargs/yargs.js:576:18)
    at /Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/mmt8048/Desktop/dev/react-ide/reactide/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactide@3.0.0 webpack-production: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactide@3.0.0 webpack-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mmt8048/.npm/_logs/2020-07-21T07_11_00_726Z-debug.log`

**Comment by WilldelaVega777** [comment]
I can't believe how such a great product is so much broken, I can't compile this, it seems to hate windows.

![image](https://user-images.githubusercontent.com/3942218/91648121-50e58800-ea29-11ea-9849-41bfd56f1acb.png)

Any ideas?

**Comment by EnricoBeltramo** [comment]
Is it a dead project? I have to start coding in react and better to know before waste time with a closed ide project

**Comment by knockshore** [comment]
[](https://github.com/microsoft/monaco-editor-webpack-plugin/issues/92)

Follow instructions in above thread.

**Comment by dvarelae858** [comment]
I manage to solve this issue:

1 -) resolve the peer depencency conflic between monaco-editor and monaco-editor-webpack-plugin
ej:
I Used these versions
"monaco-editor": "^0.19.0",
"monaco-editor-webpack-plugin": "^1.8.1"

2 -) install spawn-sync package using npm

3 -) install ttf-loader package using npm

4 -) change webpack.config.js file, search this section:
plugins: [
    new MonacoWebpackPlugin(),
  ],

and change it for this one:

plugins: [
    new MonacoWebpackPlugin({
      features: ['!gotoSymbol'],
    }),
  ],

5 -) add the following loader module config into webpack.config.js, goes into the modules->rules array

{
        test: /\.ttf$/,
        use: [
          {
            loader: 'ttf-loader',
            options: {
              name: './font/[hash].[ext]',
            },
          },
        ]
      }

6 -) run npm install
7 -) run audit fix...
8 -) execute npm run webpack-production
9 -) execute npm run electron-packager

10) that's it,

please tellme if these steps worked for you.
