### ISSUE TITLE
Exception thrown when trying to start a new project

### ISSUE THREAD

**Issue by voughtdq** [reactide/reactide#39]
**yarn -v** v0.21.3
**node -v** v7.0.0
**Operating System**: Linux local 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux
```Distributor ID: Debian
Description:    Debian GNU/Linux 9.0 (stretch)
Release:        9.0
Codename:       stretch
```
**Entry Point**: `yarn run start` and `yarn run dev`

**Description of the Problem**
When trying to create a new project, an exception is thrown. 

```
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir 'lib/temp/new-project'
    at Object.fs.mkdirSync (fs.js:855:18)
    at recurseThroughSource (/home/douglas/development/reactide/lib/copy-directory.js:23:12)
    at module.exports (/home/douglas/development/reactide/lib/copy-directory.js:32:3)
    at click (/home/douglas/development/reactide/main/menus/file.js:41:11)
    at MenuItem.click (/home/douglas/development/reactide/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/home/douglas/development/reactide/node_modules/electron/dist/resources/electron.asar/browser/api/menu.js:121:15)
```

**Expected Result**
A prompt for the creation of a new project.

**Comment by JiniHendrix** [comment]
hi there, thank you for bringing up this issue! For a temporary workaround, create an empty directory called 'temp' in directory 'lib'. Will address this issue asap.
